#!/usr/bin/env python3
"""Extract exact TSV archive members, never execute the source applets.

Build/provenance tooling only; Python and applets are not runtime dependencies.
Usage: python3 tests/bundle_sources.py [--verify] [--kjv PATH --grb PATH --vul PATH]
"""
import argparse
import hashlib
import io
import json
from pathlib import Path
import tarfile

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'src/data'


def sha(data):
    return hashlib.sha256(data).hexdigest()


def generate(tool, path):
    applet = path.read_bytes()
    marker = b'\n#EOF\n'
    _, separator, archive = applet.partition(marker)
    if not separator:
        raise ValueError(f'{path}: missing archive marker')
    with tarfile.open(fileobj=io.BytesIO(archive), mode='r:gz') as tar:
        member = tar.getmember(tool + '.tsv')
        extracted = tar.extractfile(member)
        if extracted is None:
            raise ValueError(f'{path}: TSV archive member is not a file')
        raw = extracted.read()
    spans = []
    offset = 0
    rows = 0
    books = set()
    for line in raw.splitlines(keepends=True):
        fields = line.rstrip(b'\r\n').split(b'\t', 5)
        if len(fields) == 4:  # Source subsection heading, not a verse.
            offset += len(line)
            continue
        if len(fields) != 6:
            raise ValueError((tool, offset, 'expected six fields'))
        book, alias, ordinal, chapter, verse, text = fields
        key = (book.decode(), int(chapter))
        int(verse.split(b'-', 1)[0])  # Applet %d labels retain range's first number.
        books.add(key[0])
        rows += 1
        if spans and (spans[-1][0], spans[-1][1]) == key:
            spans[-1][3] = offset + len(line)
        else:
            spans.append([*key, offset, offset + len(line)])
        offset += len(line)
    index = '// Generated by tests/bundle_sources.py; byte spans into exact TSV.\n'
    index += 'pub const Span = @import("span.zig").Span;\n'
    index += 'pub const spans = [_]Span{\n'
    for book, chapter, start, end in spans:
        index += f'    .{{ .book = {json.dumps(book)}, .chapter = {chapter}, .start = {start}, .end = {end} }},\n'
    index += '};\n'
    provenance = {'applet_path': str(path), 'applet_sha256': sha(applet),
                  'archive_sha256': sha(archive), 'member': member.name,
                  'tsv_sha256': sha(raw), 'bytes': len(raw), 'rows': rows,
                  'books': len(books), 'chapter_spans': len(spans)}
    return raw, index.encode(), provenance


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--verify', action='store_true')
    for tool, default in [('kjv', '/usr/local/bin/kjv'), ('grb', '/usr/bin/grb'), ('vul', '/usr/bin/vul')]:
        parser.add_argument('--' + tool, type=Path, default=Path(default))
    args = parser.parse_args()
    DATA.mkdir(parents=True, exist_ok=True)
    span_content = b'pub const Span = struct { book: []const u8, chapter: u16, start: usize, end: usize };\n'
    if args.verify:
        assert (DATA / 'span.zig').read_bytes() == span_content
    else:
        (DATA / 'span.zig').write_bytes(span_content)
    manifest = {'format': 1, 'sources': {}}
    for tool in ('kjv', 'grb', 'vul'):
        raw, index, info = generate(tool, getattr(args, tool))
        manifest['sources'][tool] = info
        for suffix, content in [('.tsv', raw), ('_index.zig', index)]:
            destination = DATA / (tool + suffix)
            if args.verify:
                assert destination.read_bytes() == content, destination
            else:
                destination.write_bytes(content)
        print(tool, json.dumps(info, sort_keys=True))
    content = (json.dumps(manifest, indent=2, sort_keys=True) + '\n').encode()
    destination = DATA / 'provenance.json'
    if args.verify:
        assert destination.read_bytes() == content, destination
    else:
        destination.write_bytes(content)


if __name__ == '__main__':
    main()
