"""Discover installed sources; generate catalog from observed verse labels only."""
import json
import hashlib
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOOLS = ['kjv', 'grb', 'vul']
NORMAL = {'The Acts': 'Acts', '2 King': '2 Kings', 'Sussana': 'Susanna', 'Sussana (Theodotion)': 'Susanna (Theodotion)'}

def run(tool, query):
    p = subprocess.run([tool, '-W', query], capture_output=True, check=True)
    assert not p.stderr, (tool, query, p.stderr)
    return p.stdout.decode('utf-8')

def discover():
    records = []
    for tool in TOOLS:
        listing = subprocess.check_output([tool, '-l']).decode()
        entries = []
        for line in listing.splitlines():
            name, final_alias = line.rsplit(' (', 1)
            assert final_alias.endswith(')'), line
            entries.append((name, final_alias[:-1]))
        assert len(entries) == len(set(entries)), (tool, 'duplicate listing')
        for name, alias in entries:
            # These tools prefix-match aliases. Hash the full observed output,
            # but derive metadata only from this entry's exact header block.
            output = run(tool, alias)
            headers = [l for l in output.splitlines() if l and '\t' not in l]
            rows = []
            current = None
            for line in output.splitlines():
                if not line:
                    continue
                if '\t' not in line:
                    current = line
                elif current == name:
                    rows.append(line)
            labels = [tuple(map(int, l.split('\t')[0].split(':'))) for l in rows]
            assert headers and headers[0] == name, (tool, name, headers[:3])
            chapters = sorted({c for (c, v), row in zip(labels, rows) if row.split('\t', 1)[1]})
            records.append(dict(tool=tool, name=name, alias=alias, canonical=NORMAL.get(name, name),
                chapters=chapters, maximum=max(chapters, default=0), rows=len(rows),
                duplicate_labels=len(labels)-len(set(labels)), headers=headers,
                empty_text_labels=[label for label, row in zip(labels, rows) if not row.split('\t', 1)[1]],
                output_sha256=hashlib.sha256(output.encode()).hexdigest(),
                zero_verse_labels=sorted({c for c, v in labels if v == 0})))
        assert sum(r['tool'] == tool for r in records) == len(entries), (tool, 'record loss')
        print(tool, len(entries), 'listed / fetched')
    path = ROOT / 'tests/book_discovery.json'
    path.write_text(json.dumps(records, ensure_ascii=False, indent=2)+'\n')
    return records

def generate(records):
    names = list(dict.fromkeys(r['canonical'] for r in records))
    lines = ['// Generated by tests/discover_books.py from installed -W output.',
        'pub const Entry = struct { name: []const u8, chapters: [3]u16, query_names: [3]?[]const u8, aliases: [3]?[]const u8, present_chapters: [3][]const u16 };',
        'pub const catalog = [_]Entry{']
    for name in names:
        sources = [next((r for r in records if r['canonical']==name and r['tool']==t), None) for t in TOOLS]
        def strings(field):
            return ', '.join(json.dumps(r[field]) if r else 'null' for r in sources)
        counts = ', '.join(str(r['maximum']) if r else '0' for r in sources)
        present = ', '.join('&.{' + ', '.join(map(str,r['chapters'])) + '}' if r else '&.{}' for r in sources)
        lines.append('    .{ .name = '+json.dumps(name)+', .chapters = .{'+counts+'}, .query_names = .{'+strings('name')+'}, .aliases = .{'+strings('alias')+'}, .present_chapters = .{'+present+'} },')
    lines.append('};')
    catalog_path = ROOT/'src/book_catalog.zig'
    catalog_path.write_text('\n'.join(lines)+'\n')
    subprocess.run(['zig', 'fmt', str(catalog_path)], check=True, capture_output=True)
    assert len(records)==sum(len([r for r in records if r['tool']==t]) for t in TOOLS)
    print('union',len(names),'source records',len(records))
    for r in records:
        missing = sorted(set(range(1,r['maximum']+1))-set(r['chapters']))
        if len(r['headers']) != 1 or r['duplicate_labels'] or missing or 0 in r['chapters'] or r['empty_text_labels']:
            print('ANOMALY', r['tool'],r['name'],'headers',r['headers'],'duplicates',r['duplicate_labels'],'missing chapters',missing,'chapter0',0 in r['chapters'],'empty texts',r['empty_text_labels'])

if __name__ == '__main__':
    generate(discover())
