"""Generate src/fold_table.zig: case- and accent-insensitive search keys.

Every letter in the Latin-1/Latin Extended, Greek, and Greek Extended blocks
maps to its lowercase base letter (NFD without combining marks; final sigma
folds to sigma). Letters absent from the table are treated as themselves.
Development tooling only; the generated table is committed.
Usage: python3 -I tests/generate_fold_table.py
"""
from pathlib import Path
import unicodedata

ROOT = Path(__file__).resolve().parents[1]
RANGES = ((0x00C0, 0x024F), (0x0370, 0x03FF), (0x1E00, 0x1FFF))


def folded(cp):
    char = chr(cp)
    base = ''.join(c for c in unicodedata.normalize('NFD', char) if not unicodedata.combining(c))
    base = base.lower()
    if len(base) != 1:
        return None  # e.g. ligature expansions; keep the letter as itself
    if base == '\u03c2':
        base = '\u03c3'
    return ord(base)


entries = []
for first, last in RANGES:
    for cp in range(first, last + 1):
        if not unicodedata.category(chr(cp)).startswith('L'):
            continue
        target = folded(cp)
        if target is not None and target != cp:
            entries.append((cp, target))

lines = ['// Generated by tests/generate_fold_table.py from Unicode %s data.' % unicodedata.unidata_version,
         '// Sorted (code point, folded lowercase base letter) pairs.',
         'pub const entries = [_][2]u21{']
for cp, target in entries:
    lines.append('    .{ 0x%04X, 0x%04X },' % (cp, target))
lines.append('};')
(ROOT / 'src/fold_table.zig').write_text('\n'.join(lines) + '\n')
print('wrote', len(entries), 'entries')
